"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var TxAminoPrefix;
(function (TxAminoPrefix) {
    TxAminoPrefix["MsgSend"] = "2A2C87FA";
    TxAminoPrefix["NewOrderMsg"] = "CE6DC043";
    TxAminoPrefix["CancelOrderMsg"] = "166E681B";
    TxAminoPrefix["IssueMsg"] = "17EFAB80";
    TxAminoPrefix["BurnMsg"] = "7ED2D2A0";
    TxAminoPrefix["FreezeMsg"] = "E774B32D";
    TxAminoPrefix["UnfreezeMsg"] = "6515FF0D";
    TxAminoPrefix["MintMsg"] = "467E0829";
    TxAminoPrefix["ListMsg"] = "B41DE13F";
    TxAminoPrefix["StdTx"] = "F0625DEE";
    TxAminoPrefix["PubKeySecp256k1"] = "EB5AE987";
    TxAminoPrefix["SignatureSecp256k1"] = "7FC4A495";
    TxAminoPrefix["MsgSubmitProposal"] = "B42D614E";
    TxAminoPrefix["MsgDeposit"] = "A18A56E5";
    TxAminoPrefix["MsgVote"] = "A1CADD36";
    TxAminoPrefix["TimeLockMsg"] = "07921531";
    TxAminoPrefix["TimeUnlockMsg"] = "C4050C6C";
    TxAminoPrefix["TimeRelockMsg"] = "504711DA";
    TxAminoPrefix["HTLTMsg"] = "B33F9A24";
    TxAminoPrefix["DepositHTLTMsg"] = "63986496";
    TxAminoPrefix["ClaimHTLTMsg"] = "C1665300";
    TxAminoPrefix["RefundHTLTMsg"] = "3454A27C";
    TxAminoPrefix["SetAccountFlagsMsg"] = "BEA6E301";
    TxAminoPrefix["BnbchainAccount"] = "4BDC4C27";
    TxAminoPrefix["BnbchainToken"] = "140364E6";
})(TxAminoPrefix = exports.TxAminoPrefix || (exports.TxAminoPrefix = {}));
//# sourceMappingURL=stdTx.js.map